### ISSUE TITLE
Rendered Components break page boundary

### ISSUE THREAD

**Issue by owenmonagan** [prc5/react-zoom-pan-pinch#10]
<img width="1425" alt="Screen Shot 2019-09-09 at 9 26 01 AM" src="https://user-images.githubusercontent.com/6400395/64534718-f1f0a580-d2e3-11e9-9fbf-d411f2dd5d4c.png">

There is white space which extends past the react webpage boundary. From my testing, this is because the componets within the TransformComponet are technically larger than the page boundary. The screenshot is of the TransformComponet scaled somewhere close to 0.3.

I would like the whitespace to not exist while maintaining the functionality of this wonderful react-zoom-pan-pinch component. Is there a strategy that I can employ while retaining the original structure of my components within the TransformComponent?

**Comment by prc5** [comment]
Hey! Without looking into structure of your code it's hard to say anything about the problem you faced. TransformComponent was designed to support css styling/fixes, maybe you can use it to get rid of those white spaces. You can connect styles to "react-transform-component" or "react-transform-element" classes, to limit the view to 100vw or so. If you still have some problems, let me know and we will find out how to fix it 😄

**Comment by owenmonagan** [comment]
I figured out that the issue I was having was related to tables not playing well with responsive design. I refactored my code to use material ui's grid structure ([flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)). 

One unfortunate side effect of my tableless design was when implementing the example with controls, it seems that the y axis was no longer locked. Even using the `lockAxisY` prop. Each tick of the scroll wheel switched the axis from left to right, to right to left. When implemented the `simple` example, this was not an issue.

I am using the `simple` version on the website/project I am creating. You might be interesting is seeing some examples of your component in operation. I am definitely an amateur when it comes to react & front end stuff, so I am sorry if I have butchered your baby. If you view it on mobile you will see the huge benefit I am getting from it, even if I haven't configured it well.
[Fairly large view](https://fplugin.com/tournament?2757eb92-0ff9-4ac3-a3d7-a07b1409b770)
[Smaller but with live action](https://fplugin.com/tournament?442198a5-5fba-4c60-98c5-20a5ed6e1f8d)

**Comment by prc5** [comment]
Hey, so I've fixed some of the bugs with the lib. Your problem is probably impossible to resolve with those components, if the scale is under 1 - white space will appear, and there is probably no way to do it. I hope you will get some value of using it anyway!
