### ISSUE TITLE
Calling resetTransform in parent component

### ISSUE THREAD

**Issue by cprzytocki** [prc5/react-zoom-pan-pinch#101]
Hey I can't seem to find a way to call the resetTransform function in a parent component. The only way I've done it is using buttons as seen in the Usage example.

**Comment by codeWebZhang** [comment]
same question @cprzytocki

**Comment by nguyenthetoan** [comment]
the solution at the moment is to add a hidden button then programmatically trigger `click()` on that button. It would be great if there are exported hooks to handle the zoom 🙏

**Comment by prc5** [comment]
New version added ref ;)
