### ISSUE TITLE
Apply styles to TransformComponent container

### ISSUE THREAD

**Issue by rektdeckard** [prc5/react-zoom-pan-pinch#102]
Hey, awesome library! Had a thought that it would be nice to be able to apply arbitrary styles to either the TransformWrapper, or to the TransformComponent's _container_. As an example, if you wanted to show the "move" cursor type when within the container bounds to show that an image can be panned, you might do:

```jsx
class Example extends Component {
  render() {
    return (
      <TransformWrapper>
        <TransformComponent style={{ cursor: "move" }}>
          <img src="image.jpg" alt="test" />
        </TransformComponent>
      </TransformWrapper>
    );
  }
}
```

Normally I'd just apply the style to the wrapped component, but in the case that the wrapped component is _smaller_ than the container (or zoomed way out), you don't get the cursor. In the example below, the dotted line represents the component bounds, and the whole image represents the Wrapper size.

**Good**
![Annotation 2020-03-26 201148](https://user-images.githubusercontent.com/26732044/77708349-34d34b80-6f9e-11ea-9739-b472a9322b6a.jpg)

**Not Good**
![Annotation 2020-03-26 201115](https://user-images.githubusercontent.com/26732044/77708354-3866d280-6f9e-11ea-8dce-8770dcbeaa89.jpg)

**Comment by djmisterjon** [comment]
+1 also need for hack drag-drop
need styles to force a mode absolute when drop elements inside the frame
```css
    top: x;
    left: y;
    position: absolute;
``
