### ISSUE TITLE
Issues with dragging very large div

### ISSUE THREAD

**Issue by Selean** [prc5/react-zoom-pan-pinch#103]
I'm trying to render a google-like map using this lib.
So, i have a 500x500 wrapper with map that like 5000x5000. I expects that I'm able to drag to any zone of that map like in google maps. But i can't. When i try to drag to the other end of map, it returns to initial position.
So the question:
I'am missing some props to use it this way? Or this library simple doesn't support this kind of stuff.

**Comment by rnvarma** [comment]
I'm running into the same issue.. I imagined I'd be able to render a large container of ~10,000px by ~10,000px and have the user drag around to different parts of the container.

However, what is happening is that it keeps scrolling back to the top left of the container whenever I try to move away

**Comment by dominiczy** [comment]
Have you tried setting the `limitToBounds` prop to `false`?

**Comment by max-koa** [comment]
Hi @Selean @rnvarma . Were you able to solve this somehow? @dominiczy limitToBounds does not solve this issue because it would allow people to go beyond the bounds (outside of the image). The problem is that the image's bounds are wrong, OR we are setting something wrong somehow.
