### ISSUE TITLE
resetTransform does not work properly on Firefox

### ISSUE THREAD

**Issue by WisienDot** [prc5/react-zoom-pan-pinch#104]
When the transform component has some fixed dimensions, the resetTransform function does not center the image horizontally in Firefox. Please see attached video and codesandbox example.

https://www.youtube.com/watch?v=xK__31iH0pU
https://codesandbox.io/s/distracted-field-i3oul

**Comment by QuentinMussche** [comment]
I have the same issue that the resetTransform doesn't work properly in Firefox.

In Chrome it resets the content to the center but in Firefox the content resets to the top left of the wrapper.
I've tried using the `setPositionX` and `setPositionY` which places it at the correct location but after scrolling it resets itself to the top left.
