### ISSUE TITLE
Movement is not ending on drag end.

### ISSUE THREAD

**Issue by RodolfoSarkisRocha** [prc5/react-zoom-pan-pinch#105]
When mouse button is released during drag, it do not stop it from moving.

Tried to leave only wrapper and component with img but it still has the same behavior.

Also tried setting pan={{velocity: false}}. Doesn't work either.

**Comment by Szauka** [comment]
```
 <TransformWrapper
        options={{
            limitToBounds: false
        }}>
          
         {/* rest of code */}

 </TransformWrapper>
```
Try setting this `  limitToBounds: false` like in the example above.
