### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [prc5/react-zoom-pan-pinch#106]
First of all, great package!

I am trying to make the container of an image responsive such that when the window size changes the image scales up/down accordingly and stays within the same position within the frame. 

I am guessing I need to apply a scaling factor on to the scale, positionX and positionY values in order to be able to do so. 

Has anybody tried this / got an idea of how I should implement this?

**Comment by prc5** [comment]
For images we can achieve it by styling, with the nodes, that thing will be more "tricky". I have an idea to make some sort of wrapper around it so it will adjust itself with responsiveness, but for now it's just a plan

**Comment by keneijezie-sensorup** [comment]
@prc5 Any luck or progress with making images responsive? Or any pointers will be great too! Thanks!

**Comment by prc5** [comment]
We have now responsive example thanks to @matthiasschwarz !
