### ISSUE TITLE
Get updated scale position after zooming in or out

### ISSUE THREAD

**Issue by shaneeza** [prc5/react-zoom-pan-pinch#11]
I'm currently using 

```
<button
 type='button'
 onClick={(e) => this.onZoomIn(e, scale, zoomIn)} > 
+ 
</button>
```

and inside of 
```
  onZoomIn = (e, scale, zoomIn) => {
    zoomIn(e);
    console.log(e, scale);
  }
```

This works fine except the scale that is returned is the old scale value. Is there a way that i can get the updated scale value after zooming in or out? 

or 

Is there by chance an onChange event or something similar where i can always get updated values when ever any change is made? Currently there is `onPanning`, `onWheel`, etc but there is nothing for `onZoom`.

Thanks

**Comment by prc5** [comment]
I've added onZoomChange function to the new version 👍

**Comment by dlcognite** [comment]
It seems that this is not called when you call `zoomIn`, `zoomOut` or double click still. Only when you scroll to zoom this is being called back.

**Comment by dlcognite** [comment]
https://github.com/cognitedata/react-zoom-pan-pinch fixes this

**Comment by naveenprakash74** [comment]
> I've added onZoomChange function to the new version

onZoomChange called many times. I want to get the last values {scale, positionX, positionY, previousScale}
