### ISSUE TITLE
If maxzoom is true, disable pan

### ISSUE THREAD

**Issue by walterjaworski** [prc5/react-zoom-pan-pinch#114]
Hey everybody,
i'm breaking head with this problem. Is possible disable pan if max zoom is true? How i make this?

**Comment by minhdongsss** [comment]
To make this, you should follow steps:
1. One variable maxZoom
2. One state hold currentZoom value.
3. Event catch every zoom and set value into currentZoom
4. In config pan disabled check: currentZoom === maxZoom
