### ISSUE TITLE
 How to do the same +/- scaling (ZoomIn and ZoomOut) ?

### ISSUE THREAD

**Issue by chienweiluo** [prc5/react-zoom-pan-pinch#119]
I set this on `TransformWrapper`, but after I call `zoomIn` and `zoomOut`  , the scale will not be the first value.

```
                zoomIn={{
                    step: 20,
                    animationTime: 50
                }}
                zoomOut={{
                    step: 20,
                    animationTime: 50
                }}
```

**Comment by Jwrighty** [comment]
Would also be interested in this. Have added in a display value for the scale and it's a bit odd for the user to zoom in and then out and not return to 100% for example

**Comment by Jwrighty** [comment]
Workaround I found for this for anyone that comes across it was to not use the zoomIn/zoomOut methods and instead make use of setScale and increase/decrease based on the current scale value.

**Comment by prc5** [comment]
Fixed now :)
