### ISSUE TITLE
defaultScale vs scale

### ISSUE THREAD

**Issue by shaneeza** [prc5/react-zoom-pan-pinch#12]
If i set the `defaultScale` to 2 the `scale` is still set to 1 on initial render and on component update the scale remains at the position it was at before the update. If i set the `scale` to 2 then every time my component updates the scale is set back to 2.  How can i have the scale set to 2 on initial render and not have it jump back to 2 on a component update?

**Comment by prc5** [comment]
Hey! Thanks for reporting, it's fixed now with the new version 👍

**Comment by prc5** [comment]
So you can just set defaultScale prop 😄
