### ISSUE TITLE
how can i get scale, positionX, positionY, previousScale after zoom operation stops

### ISSUE THREAD

**Issue by naveenprakash74** [prc5/react-zoom-pan-pinch#124]
I am using this code 
 =====================================
`<TransformWrapper
          {...transformWrapper}
          onZoomChange={this.onZoomChange}>
          {({zoomIn, zoomOut, resetTransform, ...rest}) => {
            console.warn('@@@@@rest', rest);
            return (
              <React.Fragment>
                <div className="tools">
                  <button onClick={zoomIn}>+</button>
                  <button onClick={zoomOut}>-</button>
                  <button onClick={resetTransform}>x</button>
                </div>
                <TransformComponent style={{flex: 1, backgroundColor: 'red'}}>
                  <Image
                    style={imgStyle}
                    source={{uri: this.props.imgUrl}}
                    onLoad={this.onLoadImage}
                  />
                </TransformComponent>
              </React.Fragment>
            );
          }}
        </TransformWrapper>
`
=========================================================
`onZoomChange = ({scale, positionX, positionY, previousScale}) => {
    if (previousScale !== scale ) {
      this.setState({scale, positionX, positionY, previousScale});
    }
  };
`

but getting this error
×
←→1 of 2 errors on the page
TypeError: Failed to execute 'requestAnimationFrame' on 'Window': The callback provided as parameter 1 is not a function

because onZoomChange function called many times.
I want to get {scale, positionX, positionY, previousScale } after zoom change

 any suggestion?

**Comment by jess-morgan** [comment]
I am also struggling with this problem, did you manage to find any solution?
