### ISSUE TITLE
how to reset with changed state 

### ISSUE THREAD

**Issue by idanelbaz** [prc5/react-zoom-pan-pinch#126]
i got 2 wrappers ,  both of them got zoom. 
i need - 
when 1 wrapper is clicked , the other one zoom need to reset. 

so my question is - 
how can control the zoom reset in useEffect ? 
or mabye a better solution.

**Comment by naveenprakash74** [comment]
it may be helpful  https://github.com/prc5/react-zoom-pan-pinch/issues/94#issuecomment-614626023
