### ISSUE TITLE
How to handle image larger than container?

### ISSUE THREAD

**Issue by patman1** [prc5/react-zoom-pan-pinch#130]
How to handle image larger than container?

**Example use case**:
Container: 800px x 400px
Image: 1600px x 1600px

**Actual**
Image isn't cropped to wrapper - adding `overflow:hidden` to parent solves this issue
Cannot zoom or pan image beyond what was initially visible. Turning bounds off removes the issue, but isn't desired.

**Expected**
Allow zoom and scroll to any image section, and respect bounds.

**Comment by naveenprakash74** [comment]
```
const ContainerHeight=800
const ContainerWidth=400
...
<Div style={{height: ContainerHeight,width: ContainerWidth,}}>
  <TransformWrapper>
    
        <TransformComponent>
          <Image
            style={{
              height: ContainerHeight,
              width: ContainerWidth,
              objectFit: "contain",
            }}
            source={{ uri: imgUrl }}
            onLoad={this.onLoadImage}
          />
        </TransformComponent>
    </TransformWrapper>
</Div>;

```

**Comment by thomai-d** [comment]
Did someone manage to get rid of the fixed width/height?
I want the div's dimensions to be relative (100%/100% or within flexbox layout).

See this example, if there's more width than height, the scrollbars appear again:
https://stackblitz.com/edit/react-ts-rc2mcx?file=index.tsx

**Comment by PaulDesiles** [comment]
> Did someone manage to get rid of the fixed width/height?
> I want the div's dimensions to be relative (100%/100% or within flexbox layout).
> 
> See this example, if there's more width than height, the scrollbars appear again:
> https://stackblitz.com/edit/react-ts-rc2mcx?file=index.tsx

What about using 100vh and 100vw instead of percentages ?
https://stackblitz.com/edit/react-ts-t2urpm

**Comment by thomai-d** [comment]
> What about using 100vh and 100vw instead of percentages ?
> https://stackblitz.com/edit/react-ts-t2urpm

The issue is, the image is part of a reponsive layout.
My current workaround is to retrieve the available width/height via js and the observer API, but it doesn't feel pretty.

**Comment by BrianLi101** [comment]
If the size of the image is known, you should be able to set values on the `TransformComponent`.

`<TransformComponent contentStyle={{ width: 1600, height: 1600}}>
{...}
</TransformComponent>`

**Comment by sanghunka** [comment]
Setting exact width and height is best practice?

**Comment by lordanubi** [comment]
Hello this works fine with "object-fit: contain" but it doesn't work as expected with "object-fit: cover;" and "overflow: visible" in the image.

Here you can find an example of the problem:

https://codesandbox.io/p/sandbox/still-wildflower-8czrrl?file=%2Fsrc%2FApp.js%3A15%2C27
