### ISSUE TITLE
Image and area inside wrapper not clickable

### ISSUE THREAD

**Issue by palika** [prc5/react-zoom-pan-pinch#135]
I'm facing the issue mentioned in #37 According to the issue it was fixed in november. I've tried it with a couple of versions but onClick events assigned to img and area elements are not executing.

Sandbox where it was reproduced: https://codesandbox.io/s/happy-fire-efyl8?file=/src/App.js 
It seems that when I'm clicking on the image or area, then the click events target will be the TrasformComponent instead of the img/area.

You can check the behavior in the sandbox above. The first image is outside of the TrasformWrapper and both the img and area click events log to the console. However at the bottom, clicking on the img and area won't fire console.logs. The button and the div which are in the TrasformWrapper as well fire their onClick events accordingly.

**Comment by ferezoz** [comment]
@palika Hello, were you able to make the clicks inside work?

**Comment by hkashif** [comment]
Same issue here. The culprit is in **src/components/TransformComponent.module.scss**
`.content img {
  pointer-events: none;
}`
This basically disables pointer events on images ... and, therefore, hover, clicks, etc. don't work on images.

To get around this, add the following style to your images:
`pointer-events: auto !important;`

**Comment by tejalc10** [comment]
I am still unable to handle click event on the image @prc5

**Comment by pranavgoel29** [comment]
> Same issue here. The culprit is in **src/components/TransformComponent.module.scss** `.content img { pointer-events: none; }` This basically disables pointer events on images ... and, therefore, hover, clicks, etc. don't work on images.
> 
> To get around this, add the following style to your images: `pointer-events: auto !important;`

This didn't help

**Comment by pranavgoel29** [comment]
I am trying to get the coordinated of the image when I click on it, but it's not working..
Want to show a popup with the coordinates of the image touch/click in a popup, can anyone help me on how to achieve this.
