### ISSUE TITLE
Zoom in and out slows down when parent element width is increased.

### ISSUE THREAD

**Issue by ahsan-sabir** [prc5/react-zoom-pan-pinch#141]
I have a site with a sidebar and a main panel with transform component. The issue is whenever the sidebar closes, the main panel width becomes 100%, which somehow renders zoom in and out speed quite slow. Below I have replicated the same behavior in the demo example.

https://youtu.be/99Z16DtxQvM

**Comment by confrodog** [comment]
Yes I am having a similar issue where I have the TransformWrapper/Component in the middle of my application and when I expand its width, the same issue happens to me.

**Comment by ahsan-ih** [comment]
@confrodog have you found any solution?

**Comment by ahsan-sabir** [comment]
@confrodog have you found any solution?

**Comment by confrodog** [comment]
I don’t have any surefire solution but I kept playing around with divs and where the TransformWrapper/Component was on the DOM hierarchy and it doesn’t seem to do it anymore. It’s probably not what you want to hear but I’m a novice React programmer.

**Comment by pahans** [comment]
@ahsan-sabir you can set a higher wheel step value like `wheel={{ step: 100 }}` as a temporary solution.
@prc5 I can work on this issue and this https://github.com/prc5/react-zoom-pan-pinch/issues/123. 
as I understood, seems we have an issue in the zoom sensitivity step.
