### ISSUE TITLE
Sync zooming, panning and pinching

### ISSUE THREAD

**Issue by demonmovch** [prc5/react-zoom-pan-pinch#142]
Hello. Thanks for the great package. Is it possible to zoom, pan and pinch two images simultaneously so when I zoom one image the other one will take the same position or scale. I was not able to implement this on my own. Do you have any example or advice?

**Comment by demonmovch** [comment]
do not alredy need

**Comment by saidmoya12** [comment]
Maybe you can use my answer to #159 
I hope can help you

**Comment by kimohyeong** [comment]
Is it possible in version 2.1.3?
I cannot find soultion in a previous issue.

**Comment by prc5** [comment]
Yes, we can do it via ref, where we can access current values for scale and position so you can add it via css with translate and scale properties. The other way is to wrap page with the wrapper, so you can access it's values with hooks

**Comment by rafyzg** [comment]
Does someone has snippet example of making this feature? 
It seems like using hooks is the right way to go, but I am unable to make it work.

**Comment by RodrigoGarciaLab** [comment]
Hey @rafyzg, I had to solve the same issue a few days ago and built this sandbox with a solution. Hope it helps you!

https://codesandbox.io/s/red-monad-kbj1lr?file=/src/App.tsx

**Comment by rafyzg** [comment]
@RodrigoGarciaLab 
Thank you very much!
