### ISSUE TITLE
Scale based on positionX and positionY is not working

### ISSUE THREAD

**Issue by suriyakrish** [prc5/react-zoom-pan-pinch#149]
Tried passing the X and Y axis like below.

    <TransformWrapper pan={panOpts}
                      defaultScale={2}
                      positionX={200}
                      positionY={100}>
    ....
   </TransformWrapper>

Also tried passing negative value for positionX and positionY. No luck.

**Comment by Karhide** [comment]
Thanks, I'll take a look at this soon and see if I can re-produce.

**Comment by brezodani** [comment]
I have the exact same issue as well, I haven't been able to affect the position of the image if I set the scaling.

**Comment by brezodani** [comment]
I was able to "fix" the issue locally by changing `wrapperComponent.offsetWidth` to `!wrapperComponent.offsetWidth` in StateProvider (pls see the attached image), as the logic inside the if statement overrides the transform statement. I don't know if this really a mistake, or some functionality I just don't use, so please take my fix with a grain of salt on it. In my case, which is really similar to @suriyakrish 's usage, it solved the problem.

![Screenshot 2020-10-27 at 11 57 47](https://user-images.githubusercontent.com/20615100/97292941-37579580-184c-11eb-8de4-3bd7dfcdae61.png)

**Comment by InfamousStarFox** [comment]
Try adding the following options
```
<TransformWrapper
  pan={panOpts}
  defaultScale={2}
  positionX={200}
  positionY={100}
  options={{
    centerContent: false,
    limitToBounds: false
  }}
>
```

See https://github.com/prc5/react-zoom-pan-pinch/issues/34#issuecomment-796131576
