### ISSUE TITLE
Once you set doubleClick for a TransformWrapper, how do you allow children components to also receive doubleClick events?

### ISSUE THREAD

**Issue by AndrewJudson** [prc5/react-zoom-pan-pinch#155]
I have a TransformWrapper with doubleClick set to {mode: "zoomIn"}. This has children components that have registered an onDoubleClick handler (a simple console.log to see if it registered the click event). However, when I click it it only zooms in and does not log. However does work if I set doubleClick {disabled: true} in the TransformWrapper. I would like the event to register for both, or only for the child component (if I use stopPropagation). What do I need to do to accomplish this? To me expected behavior is the event is handled for both.

**Comment by prc5** [comment]
New version added "excluded" array of tags or classNames for double click
