### ISSUE TITLE
OnWheel not always triggered

### ISSUE THREAD

**Issue by shaneeza** [prc5/react-zoom-pan-pinch#16]
I've noticed since the last update that OnWheel is not always triggered and the component does not scale. I have to drag the component a little then i'm able to zoom again. If i revert back to the older version of the code then it works fine.

**Comment by prc5** [comment]
I see, will fix it soon!

**Comment by piciuok** [comment]
wheelTime in StateContext is problem - set in vendor (:D) to 0 solve problem.

**Comment by prc5** [comment]
> wheelTime in StateContext is problem - set in vendor (:D) to 0 solve problem.

Yeah, but that was kind of "hack" solution, this time is needed to fire another event - when wheel stops. Solution is ready, will release new version today 👍
