### ISSUE TITLE
Is there any way that the library allows user selecting text?

### ISSUE THREAD

**Issue by anhthii** [prc5/react-zoom-pan-pinch#160]

**Comment by farukparhat** [comment]
Hi, was there work around for this?
Did you find a solution? @anhthii

**Comment by kayoroxa** [comment]
> Hi, was there work around for this? Did you find a solution? @anhthii

Put this in your global css, it will resolve:
.transform-component-module_wrapper__SPB86 {
  -webkit-user-select: auto !important;
  user-select: auto !important;
}

**Comment by LenniM** [comment]
Hi - is there an update to the possibility of selecting text elements or a workaround? I tried excluding the text elements from the panning motion and disabling the TransformWrapper in whole, but nothing made an effect on selecting normal text. Help is appreciated, thank you.
