### ISSUE TITLE
Double clicking on full zoomed in view should reset the view

### ISSUE THREAD

**Issue by taha-boxwala** [prc5/react-zoom-pan-pinch#161]
We are working on a project where we are allowing double click to zoom-in on an image. In case the image is already in full zoomed-in state & then if user double clicks on it then it should reset the view of the image.

**Comment by taha-boxwala** [comment]
I would like to take this up for a fix. @prc5 will you please let me know if this is an expected behavior. Have already gone through the library, will make the changes once you approve on the behavior.

**Comment by nestlist** [comment]
+1 for this behaviour

**Comment by alainib** [comment]
this is now available  👍 

 ```
<TransformWrapper
        options={{
          maxScale: 6,
          limitToBounds: false,
          limitToWrapper: false,
          wrapperClass: classes.myWrapperClass,
          contentClass: classes.myWrapperClass,
          centerContent: true
        }}
        doubleClick={{
          mode: 'reset'
        }}>
        <TransformComponent>
          <img src={imageUrl} className={classes.image} />
        </TransformComponent>
      </TransformWrapper>

```
