### ISSUE TITLE
Needs better documentation

### ISSUE THREAD

**Issue by JamesTheBald** [prc5/react-zoom-pan-pinch#175]
Great tool but the documentation is too thin. Better documentation would help more developers use this tool more easily. Specifically, instead of just listing all the props and values returned by TransformWrapper, it'd be much more helpful to explain them and their proper usage, with example code. Another complete example app, with lots of commenting, would also help.
Thank you!

**Comment by cdutson** [comment]
I second this. An example is something like positionX or defaultPositionX. if I set that to 0, where am I being positioned?

**Comment by InfamousStarFox** [comment]
Yeah, basic things like how to call zoomIn() or setTransform() from outside of the TransformWrapper really need to be documented

**Comment by gu-ru** [comment]
@InfamousStarFox 
Hi, do you know how to address blow issue?
https://github.com/prc5/react-zoom-pan-pinch/issues/182

I am facing the problem you mentioned in your comment and I asked if you know how.
