### ISSUE TITLE
Pinch not working on Child Elements of TransformComponent

### ISSUE THREAD

**Issue by stevewirig** [prc5/react-zoom-pan-pinch#176]
Everything is working great with TransformComponent zoom on Chrome / Mac.  It also is working well to pinch within iOS Safari.  That is until I add a few dynamically loaded children components that sit within the main Transform Component div container.  I can pinch the background areas/margins that are not covered with the children elements and it works fine.  If I pinch on the child component it hangs.  

> <TransformComponent>
    <TransformComponent>
      <div className="overflow-auto w-screen pt-24">
         <div id="compositionCanvas">
           <div onClick={e => handleTimelineClick(e)}>
             {[...Array(timelineSectionCount+8)].map((elementInArray, index) => (
               <VerticalRulerSection key={index} index={index}/>
             ))}
           </div>
             {tracksData.map((value, index) => {
               return <AudioTrack key={index} track={value} index={index}/>
             })}
         </div>
       </div>
     </TransformComponent>

If I pinch on top of the <AudioTrack> or the <VerticalRulerSection> child components, it hangs and does not pinch to zoom like it does outside of those components.  Thoughts?

**Comment by marwaSZ** [comment]
Hello, I have the same problem, Did you manage to fix this ? 
Thanks

**Comment by stevewirig** [comment]
I haven't solved it yet.  I have put this bug in the backlog for now and hope to fix soon.

**Comment by Knaackee** [comment]
Is this solved? I have the same problem. 

Thanks!
