### ISSUE TITLE
how to disable fling of image

### ISSUE THREAD

**Issue by onehorry** [prc5/react-zoom-pan-pinch#18]
Is there any function or variable can disable fling, which is when user drag image to one direction and the image will keep moving and slow down until stop.
![image](https://user-images.githubusercontent.com/55473741/65105776-a4bdb380-da08-11e9-9da4-c1a25ed7f54d.jpg)

**Comment by prc5** [comment]
enableVelocity={false}
velocityTimeBasedOnMove={false}
velocityAnimationSpeed={0}
minVelocity={0}
minVelocityScale={0}
velocitySensitivity={0}

**Comment by onehorry** [comment]
Hello!
I try you say issues ,but not work
I want stop drag move animation like bottom gif 
Thank your help~

![moveanimation](https://user-images.githubusercontent.com/55473741/65412404-bbf20c00-de21-11e9-87b8-7365e5774b51.gif)
