### ISSUE TITLE
can wheel zoom in to a scale more the 8? 

### ISSUE THREAD

**Issue by nadavtal** [prc5/react-zoom-pan-pinch#180]
I see the the wheel can scale up to 8 maximum. i try wheel={{
                    wheelEnabled: enableWheel,
                    touchPadEnabled: enableTouchPadPinch,
                    limitsOnWheel : false,
                  } 
but with no change
how can i unlimit the wheel zoom?
Thanks

**Comment by InfamousStarFox** [comment]
Min and max scale is set in the options field. Try
```
<TransformWrapper
  options={{
    minScale: 0.5,
    maxScale: 15
  }}
>
```
