### ISSUE TITLE
How to call resetTransform() from outside of the TransformWrapper?

### ISSUE THREAD

**Issue by syamama** [prc5/react-zoom-pan-pinch#182]
I am facing problem that mentioned in the title.
Does anyone know how to address this issue?

**Comment by InfamousStarFox** [comment]
What I ended up doing was place the function call inside an onClick of a hidden button element, and then trigger the button click via useRef.

If you can find a better method, please let me know as this work around feels hacky

**Comment by gu-ru** [comment]
@InfamousStarFox 
Thanks for your reply! I could implement by click hidden button via useRef. This seems to be the best way to do it right now.
