### ISSUE TITLE
Possible to make overflow optional ?

### ISSUE THREAD

**Issue by alexkhalevine** [prc5/react-zoom-pan-pinch#186]
Right now image container `.react-transform-component` have hardcoded `overflow: hidden` inside of `TransformComponent.module.css`, that prevents users from letting image scale outside of it's wrapper, would this be possible to have this overflow setting as an option ?

**Comment by always-akshat** [comment]
I know this was closed but is there a way to do it with the current version?

**Comment by carlagomesah** [comment]
I'm also interested in overriding overflow. Any ideas?
