### ISSUE TITLE
I will get x offset when scaling to left

### ISSUE THREAD

**Issue by onehorry** [prc5/react-zoom-pan-pinch#19]
Hello,

I use div to encapsulate your div of react-transform-element, and if I use mouse wheel to zoom in our content, your div will get x offset so the content will move to left.
Is there and idea can solve this issue?
![screenshot1](https://user-images.githubusercontent.com/55473741/65109807-0b43d100-da0b-11e9-860c-8943d2653232.jpg)
![screenshot2](https://user-images.githubusercontent.com/55473741/65109835-10088500-da0b-11e9-91c3-f7622a1f85d0.jpg)

**Comment by onehorry** [comment]
sorry, forget to mention this, the mouse cursor is in center of content view, so I think the zoom in should also  align in center of content view, but it will move to left

**Comment by prc5** [comment]
Will fix this one soon, thanks for reporting 👍
