### ISSUE TITLE
Cannot zoom by using zoomIn zoomOut button

### ISSUE THREAD

**Issue by posawatpeem** [prc5/react-zoom-pan-pinch#204]
2.0.0 version to latest version cannot zoom in -out by button

**Comment by alexomon018** [comment]
No wonder package 1.6.1 has the most downloads.

**Comment by prc5** [comment]
https://prc5.github.io/react-zoom-pan-pinch/?path=/story/examples-controls--controls

Is this example working for you? or can you give me more details?

Because as I'm clicking right now - it looks fine

**Comment by prc5** [comment]
> No wonder package 1.6.1 has the most downloads.

Feel free to help ;)

**Comment by jackwlee01** [comment]
When I upgraded to 2.X my zoom buttons also stopped working.

I had to wrap my onClick in order to get them working again, like so:

onClick={()=>zoomIn()}

**Comment by nodepond** [comment]
I had the same issue. Would be great to update the examples in the docs.

**Comment by posawatpeem** [comment]
@jackwlee01 this prob is solved by your method thanks

**Comment by prc5** [comment]
I will take a look this weekend and update everything, thanks guys!

**Comment by prc5** [comment]
Fixed - update to docs got pushed :)
