### ISSUE TITLE
zoomToElement appears to not function when selection Element inside of SVG

### ISSUE THREAD

**Issue by Tylermarques** [prc5/react-zoom-pan-pinch#215]
When passing the ID of a <polygon> element inside an SVG to the `zoomToElement` function as a string (or as the `event.target` object of a click event) no transformation occurs.

Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)

package.json
```
...
"dependencies": {
    "@material-ui/core": "^4.11.4",
    "@material-ui/icons": "^4.11.2",
    "@types/react": "^17.0.11",
    "@types/react-dom": "^17.0.8",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-pdf": "^5.3.0",
    "react-scripts": "^4.0.3",
    "react-zoom-pan-pinch": "^2.1.1",
    "typescript": "^4.3.4",
}
...
```

My code:

```
import React from 'react';
import {ReactComponent as ActualSVG} from '../assets/someSVG.svg'
import {TransformWrapper, TransformComponent} from "react-zoom-pan-pinch";
import {Button} from "@material-ui/core";

function SVGComponent
return (
            <TransformWrapper initialScale={1}
                              limitToBounds={false}
                              centerOnInit={true}
                              minScale={0.5}
            >
                {({zoomToElement, resetTransform}) => (
                        <TransformComponent>
                            <Button onClick={()=>zoomToElement("Box_2")}/>
                            <div>
                                <ActualSVG />
                            </div>
                        </TransformComponent>
                )}
            </TransformWrapper>
    )
}
```

When clicking the <Button> I was expecting the wrapped SVG to zoom to the element with the id "Box_2" but no transformations occur. If I continue to click the <Button> every 3-4 times an error is logged in console saying "No mouse or touch offset found". 

Please let me know if there is anything more I can provide.

**Comment by prc5** [comment]
Unfortunately I am currently unable to implement svg support in this function. The problem is that svg elements do not contain offsetParent, offsetWidth etc. I do not know if using getBoundingRect will be possible in this case, currently I do not see a good solution to this issue

**Comment by Tylermarques** [comment]
Okay thank you for your efforts and thank you for this library. It has been a major help in my projects. I will see if I can get anything to work and submit a PR if I can.

**Comment by alexomon018** [comment]
Have the same problem here as @Tylermarques , any updates maybe?

**Comment by Tylermarques** [comment]
@alexomon018 I don't believe @prc5 is able to work on this at this time. If you know of a solution please submit a PR and it'll help us all out.

**Comment by im-amir** [comment]
@Tylermarques were you able to get around this please?

**Comment by Tylermarques** [comment]
@im-amir No solution at this time.

**Comment by ggomaeng** [comment]
I was trying to solve this issue too and found a workaround this issue, but it's kinda hacky.

I created a separate div container that only holds divs, which are mapped to the x, y positions of each svg elements.

Not the best solution, but works!

![image](https://user-images.githubusercontent.com/18402191/193293620-8bdaa553-3011-4d76-9d3e-51079ab8baec.png)

**Comment by prc5** [comment]
@Tylermarques @ggomaeng @im-amir @alexomon018 Hey guys, thanks for your work and testing this out. I believe, I finally solved this issue in the 2.5.0 version. Now we can zoom to absolutely any element! 🎉🎉

Here is the demo: https://prc5.github.io/react-zoom-pan-pinch/?path=/story/examples-svg-zoom-to-element--svg-zoom-to-element

**Comment by Tylermarques** [comment]
@prc5 Thanks so much for implementing this! Really appreciate the time and effort you put into this project! :)

**Comment by alexomon018** [comment]
@prc5 Amazing work mate! Keep it going I really appreciate it!

**Comment by leonardomorenozaga** [comment]
seems docs need some update?
> It allows only to zoom elements with offsetWidth and offsetHeight properties - since SVG's doesn't have those, it is impossible to perform it on such elements.
