### ISSUE TITLE
Image is blurred when zoomed on iPhone

### ISSUE THREAD

**Issue by QBGROUP** [prc5/react-zoom-pan-pinch#216]
On my mac if I zoom the image quality is fine, but when I do the same on iPhone (tested both with safari and chrome) the image is blurred, the quality is not the one of the original image, it's just the rendered image zoomed in, with low quality.
I don't understand if it's a bug, a limitation of mobile browser or something I'm doing wrong.
Thank you

**Comment by prc5** [comment]
I believe that's not connected to the library since I'm doing only css transformations here :) If you find something related to the lib itself, make a new issue and let me know
