### ISSUE TITLE
./node_modules/react-zoom-pan-pinch/dist/index.esm.js Module not found

### ISSUE THREAD

**Issue by HarryF514** [prc5/react-zoom-pan-pinch#218]
./node_modules/react-zoom-pan-pinch/dist/index.esm.js
Module not found: Can't resolve 'react/jsx-runtime' in '/node_modules/react-zoom-pan-pinch/dist'

**Comment by prc5** [comment]
@HarryF514 have you found solution to this or it is still a problem for you? Have you tried to reinstal node_modules?

**Comment by zduford** [comment]
I'm having the same issue as well, running React v16, reinstalled my node_modules and it is still occurring.

**Comment by HarryF514** [comment]
> @HarryF514 have you found solution to this or it is still a problem for you? Have you tried to reinstal node_modules?

I removed node_modules folder, reinstall, still seeing the issue.
