### ISSUE TITLE
Image map disabled

### ISSUE THREAD

**Issue by skyheat** [prc5/react-zoom-pan-pinch#219]
Not sure if I'm doing something wrong or this is intended but using this library disables an image's map, eg. nothing on the image can be clicked.
 
```
<TransformWrapper>
                <TransformComponent>
                  <img src={mapImg} alt="Island" useMap="#islandmap"/>
                </TransformComponent>
</TransformWrapper>
```

**Comment by prc5** [comment]
@skyheat Honestly it shouldn't be blocked inside the transform components, I will take a look and fix it, thanks!

**Comment by skyheat** [comment]
@prc5 solved! Thanks :)

 Issue #135
