### ISSUE TITLE
Having the compontent rendered makes all sliders unslideable

### ISSUE THREAD

**Issue by danieldimit** [prc5/react-zoom-pan-pinch#22]
I've stubled upon a very interesting bug. If you have the react-zoom-pan-pinch component anywhere rendered on the screen, all input html elements of type range would no longer be slide-able. You can click on them to change their value, but sliding (click and drag) them does nothing.

Here is sample code of slider that would no longer work if you have used the component:
```
import React, { Component } from 'react';

class GeneralOpt extends Component {
    constructor(props) {
        super(props);
        this.state = {
            to: -39
        };
        this.handlePoseChange = this.handlePoseChange.bind(this);
    }

    handlePoseChange(event) {
        let state = {to: event.target.value};
        this.setState(state);
    }
    render() {
        return (
            <div id="sidebar-container">
                <input
                    id="to"
                    type="range"
                    min="-100"
                    max="100"
                    value={this.state.to}
                    onChange={this.handlePoseChange}/>
            </div>
        );
    }
}

export default GeneralOpt;
```

Text selection (click and drag on a text) also seems to not work. I guess the component is tapping into the sliding event of the whole page somehow. It would be nice if the sliding worked as expected everywhere except over the react-zoom-pan-pinch component.

Thank you for the nice tool

**Comment by prc5** [comment]
Thanks for this issue! I will take a closer look on the topic this weekend while rewriting of lib 👍 😄

**Comment by prc5** [comment]
So after checking it, I found out that I made it because of many bugs/problems it was causing while panning. To solve this problem, you can make selecting or copying the text by some button inside which will add window selection. Or disable panning in my lib and disable user-select css class on TransformComponent class, this will allow you to select text.
