### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Achder** [prc5/react-zoom-pan-pinch#221]
I love to see that you're working on the project again.
But could you provide a changelog somewhere? You seem to have made a lot of changes but I can't get an overview.

**Comment by prc5** [comment]
I will start adding changelogs to the project, I think it may be impossible to do it for switch from 1.6.1 - since I completly rebuild it, I would think about it as a new library with some similarities - there is simply to much for me to spend so much time over it :(
