### ISSUE TITLE
Very laggy on desktop

### ISSUE THREAD

**Issue by joel1st** [prc5/react-zoom-pan-pinch#224]
The storybook is very laggy on desktop when panning (latest chrome and firefox on windows and linux) (sometimes as low as 4-5 FPS according to profile). It runs very smoothly on my android device running the latest chrome. v1.6.1 runs very smoothly on desktop, so perhaps a recent regression.

**Comment by cdutson** [comment]
This might be closed, but I'd like to note that the panning is not really working on desktop, and lag does seem to be at least a symptom of this. I've had to revert to 1.6.1 (as listed above) in order to rectify.
