### ISSUE TITLE
Image with fixed width and height

### ISSUE THREAD

**Issue by shaneeza** [prc5/react-zoom-pan-pinch#23]
From what i can see this library is meant for images with a width of 100% of the container. Using an image with a fixed width and height doesn't fully pan since its calculating for an image that is meant to be 100% of the container. I can fix this by setting `limitToBounds` to false so that i can pan it but then by doing this you can pan the content off the screen. Is there a way to use an image with a fixed width and height while sticking to the limit bounds? 

Thanks.

**Comment by prc5** [comment]
Yes, you can try to put your image into div and style it inside as you want 👍

**Comment by shaneeza** [comment]
https://im3.ezgif.com/tmp/ezgif-3-bc00ea4c1fbd.gif

I think the question might of been confusing. The gif above illustrates my question. The image is larger than the viewport so when i zoom in a little i can pan but its not panning all of the image. If i resize the browser you can see that there is more of the image to the right that you're not able to pan.

**Comment by prc5** [comment]
You have to use some css styling for that - object-fit / width / height styling, image must be contained inside of the wrapper

**Comment by shaneeza** [comment]
That answers my question, It wont work as intended with an image larger than the wrapper. Thanks for the reply, i appreciate it!
