### ISSUE TITLE
image fuzzines on zoom in version 2

### ISSUE THREAD

**Issue by justinhehli** [prc5/react-zoom-pan-pinch#230]
I recently migrated from version 1.6.1 to 2.1.3. In my application, I have an html-svg overlaying a png image inside the TransformWrapper / TransformComponent. On zooming, I expected the png to look fuzzy, not so much the svg. The svg contains points and polygons (with edges), and on the slightest zoom or drag, they look very fuzzy and not sharp anymore.

In the old version 1.6.1, this was not as extreme as in the new 2.1.3, which is why I noticed it in the first place. Definitely a downgrade if one tries using svg, to e.g. make zoomable maps on which users can draw polygons (my use case). Also, the underlaying png image is definitely less sharp zoomed than in the old version.

I attached two sceenshot of the same map / polygon clipping, once version 1.6.1, once version 2.1.3.

Thanks for checking it out in advance!

![Version_1 6 1](https://user-images.githubusercontent.com/36924774/129558847-9ba86abb-796b-4e34-8606-b8dc575155f5.png)
![Version_2 1 3](https://user-images.githubusercontent.com/36924774/129558851-26e84f75-04d0-484b-a277-bb4bd3968310.png)

**Comment by SelfDevTV** [comment]
Is this maybe related to my issue #231 ?

**Comment by justinhehli** [comment]
> Is this maybe related to my issue #231 ?

I would guess so, from the pictures it seems to be about the same problem. Even a normal png image gets more blurry than in the old version for me.

For now my tip is to downgrade to 1.6.1, the functionality is the same (as far as I noticed) and it is not blurry. Some of the TransformWrapper props in v2 are burried in an "options" object prop in v1 but oh well. If you are working with React v17, you can still install the 1.6.1 version of this library with the --legacy-peer-deps option and it still works.

**Comment by SelfDevTV** [comment]
@justinhehli  Thx I'll give that a try.

**Comment by prc5** [comment]
Fixed!
