### ISSUE TITLE
Jumpy Image Rendering When Using `centerOnInit`

### ISSUE THREAD

**Issue by JeffThorslund** [prc5/react-zoom-pan-pinch#232]
The `centerOnInit` prop is causing a jumpy/choppy/irregular loading experience.

In my use case, the `<TransformWrapper />` is larger than the `<TransformComponent />`, and the `centerOnInit` prop is being used to center the image.  The image initially renders in the top left corner, then immediately shifts to the middle of the screen. This quick visible image shift is unexpected and gives the appearance of a "choppy" loading experience. 

**To reproduce**, press the refresh button on the Code Sandbox built-in browser, and observe the image appearing in the top left corner, then immediately shifting to the middle of the screen. 

https://codesandbox.io/s/adoring-moon-3wogd?file=/src/Viewer.js

Any insights on why this is happening, or workaround would be appreciated.

**Comment by apopelyshev** [comment]
Observing the same issue. In my case I need to dynamically calculate the `minScale` prop depending on the inner image resolution, so I tried utilising `centerOnInit` or the `onInit` handler. The latter does seem to work (just updating the state variable fed into the `minScale`), but during the _first_ load of some random _new_ picture, I get the described issue - rendered small, in the top left corner.

**Comment by apopelyshev** [comment]
Ok, my use-case may seem pretty weird but I managed to mitigate the behaviour I was experiencing. Something like that makes it work for me (just in case someone finds useful bits):

```
const [minScale, setminScale] = useState(1.0);
const transformRef = useRef(null);

const mainImgRef = (img) => {
	const ref = transformRef.current;
	if (img && ref && ...) {
		const newScale = ...
		setminScale(newScale);
		ref.resetTransform();
		ref.centerView(newScale + 0.002);
		...
	}
}

return (
	<TransformWrapper
		ref={transformRef}
		minScale={minScale}
		doubleClick={{ disabled: true }}
		zoomAnimation={{ disabled: true }}
	>
		{() => (
			<TransformComponent>
				<img src={...} alt='...' ref={mainImgRef} />
			</TransformComponent>
		)}
	</TransformWrapper>
)
```

**Comment by JeffThorslund** [comment]
@apopelyshev I tried to copy the `ref` setup that you have but didn't fine away to change the behavior. Would you mind linking a code sandbox with a quick example of this `ref` configuration fixing the jumpy image loading issue? It would be much appreciated!

**Comment by Sanster** [comment]
@JeffThorslund Have you found a way to solve the problem?
