### ISSUE TITLE
Wheeling and moveing content to left side boundary problem

### ISSUE THREAD

**Issue by onehorry** [prc5/react-zoom-pan-pinch#24]
Hello!~
I try setting your plugin scale positionX positionY like below code.
`<TransformWrapper minScale={1} maxScale={5} scale={s} positionX={x} positionY={y}>`

But problem like below gif.

![wheelmoveproblem](https://user-images.githubusercontent.com/55473741/65413437-08d6e200-de24-11e9-8548-a21176d7c2b7.gif)

Thank your help~

**Comment by mpyrc** [comment]
Could you post gif one more time? It is not working anymore :/

**Comment by prc5** [comment]
Fix is on it's way, today will release new version.
