### ISSUE TITLE
Input field inside transform component is not typeable.

### ISSUE THREAD

**Issue by sudipstha08** [prc5/react-zoom-pan-pinch#246]
If we put the input field inside the transform component, the field `input` &` textarea` is not typeable.
React: 17.0.1
```html
<TransformComponent>
      <image />
      <input />     
  </TransformComponent>
```

Env
```
 react: 17.0.1
 react-zoom-pan-pinch: 2.1.3,
```

**Comment by viveksharmapoudel** [comment]
I am also facing the same issue, Input button and textarea is not working

**Comment by kenjim83** [comment]
@bhsz thank you!  This solved my problem.

**Comment by rkvirajgupta** [comment]
@bhsz Thankyou
