### ISSUE TITLE
Right-click to Save Image

### ISSUE THREAD

**Issue by wisefool769** [prc5/react-zoom-pan-pinch#249]
After wrapping my image in the TransformWrapper, web browsers seem not to recognize it as an image anymore. When I right-click the image, the usual image-specific context menu including "Save Image As" is not present. 

You can see this in the [demos](https://prc5.github.io/react-zoom-pan-pinch/?path=/story/examples-big-image--big-image) as well. 

![Screen Shot 2021-10-03 at 8 13 18 PM](https://user-images.githubusercontent.com/3916546/135778315-53fc0eae-9eff-4cbc-bf7f-8d958651b767.png)

Is there some way to preserve users' ability to right-click the images? 
In my use-case I wrap a grid with multiple images in a TransformWrapper.

**Comment by sjdemartini** [comment]
@wisefool769 I found this suggested workaround solves the problem for me https://github.com/prc5/react-zoom-pan-pinch/issues/135#issuecomment-683463453
