### ISSUE TITLE
[Mobile Safari] Jerks on slow panning, even on your demo (video)

### ISSUE THREAD

**Issue by devXpro** [prc5/react-zoom-pan-pinch#263]
Panning works smoothly when you pull quickly with your finger, but it jerks when you pull slowly with your finger.

https://youtube.com/shorts/weaehvMdLTY?feature=share

**Comment by devXpro** [comment]
Here is solution:
https://github.com/prc5/react-zoom-pan-pinch/pull/247

**Comment by janaagaard75** [comment]
This should now have been fixed here https://github.com/proNestorAps/react-zoom-pan-pinch/pull/64.

**Comment by prc5** [comment]
Fixed in new version
