### ISSUE TITLE
Is there support to react 15

### ISSUE THREAD

**Issue by RajuTicvic** [prc5/react-zoom-pan-pinch#273]
Hi,
Can I use the package for the react v15? because I just got errors when I use the latest version of react-zoom-pan-pinch.

thanks

**Comment by jelizarovas** [comment]
i've upgraded to v17 react and react scripts 5 - it's not working anymore

**Comment by royair** [comment]
same here....

**Comment by jelizarovas** [comment]
https://github.com/prc5/react-zoom-pan-pinch/pull/266
