### ISSUE TITLE
activation keys not working

### ISSUE THREAD

**Issue by netanelvaknin** [prc5/react-zoom-pan-pinch#274]
Hi :)
I was trying to use activationKeys prop with different keys to allow the wheel only with them.
for example:
allow wheeling only when alt is pressed.
```
 <TransformWrapper
            initialScale={1}
            maxScale={2}
            wheel={{step: 0.4, activationKeys: ["18", "alt"]}}
            doubleClick={{disabled: true}}
            onWheel={({state: {scale}}) => setCurrentZoom(scale)}
          >
```

The actual result is that it's disabled the wheel option completely.

**Comment by jpggvilaca** [comment]
+1

**Comment by wildseansy** [comment]
For what it's worth this works for me

```typescript

 <TransformWrapper
   wheel={{ step: 0.4, activationKeys: ["z"] }}
/>
```

**Comment by xStarman** [comment]
It uses `KeyboardEvent.key` to check wich key is being pressed. So you need to set "Alt" with first uppercase.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
