### ISSUE TITLE
Pan on x-axis doesn't work

### ISSUE THREAD

**Issue by sikandarchishty** [prc5/react-zoom-pan-pinch#282]
Hi, I have a very wide div, basically I am making a Family Hierarchy so it will get as wider as possible.
However, for a very wide Div, I cannot pan on x-axis.

[CodeSandbox](https://lvnggw.csb.app/)

The only it Pan on X-axis works is if its zoomed-in and then you can pan left and right.

The styles are a bit off here but I guess its irrelevant for this issue.

**Comment by amitgaikwad1031996** [comment]
+1. Any solutions found so far?

**Comment by paolojulian** [comment]
Up

**Comment by prc5** [comment]
Issue is related to the `.react-transform-wrapper` width. You need to control it with max-width so it will fit in the screen.

Solution:

```css
.react-transform-wrapper {
   max-width: calc(100vw - 80px);
}
```
