### ISSUE TITLE
Support for React 18

### ISSUE THREAD

**Issue by balub** [prc5/react-zoom-pan-pinch#292]
The library seems to not work with the latest React 18. Support for it will be great.

**Comment by janaagaard75** [comment]
> I bumped the peer deps to v18 and it seems to still work fine. Hopefully the author can do the same!

Did you also change how React is rendered? Without this change, then React 18 was running in React 17 mode. See [Updates to Client Rendering APIs](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis).

**Comment by janaagaard75** [comment]
I have added React 18 as a peer dependency to [@pronestor/react-zoom-pan-pinch](https://www.npmjs.com/package/@pronestor/react-zoom-pan-pinch), so that package is now compatible with React 18.

Just as @paullewisn, I didn't find any issues, also not when rendering in React 18 mode.

**Comment by paullewisn** [comment]
Thanks @janaagaard75 🔥

**Comment by automatensalat** [comment]
For anyone coming here after upgrading to React 18: Until support for React 18 is released you can override the peer dependency version if you use `npm 8.3+`:

```
// package.json
{
  "dependencies": {
    ...
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
  },
  "overrides": {
    "react-zoom-pan-pinch": {
      "react": "$react",
      "react-dom": "$react-dom"
    }
  }
}
```
The `$react` placeholder then uses the version in your dependency definition. You can also specify the version directly. For this particular dependency overriding to v18 seems to work fine.
