### ISSUE TITLE
Image size is cutting, not zooming for full length

### ISSUE THREAD

**Issue by zahiruldu** [prc5/react-zoom-pan-pinch#293]
I am trying to see the full width and length of the image while zooming, But it only zoom on what has been rendered as initial look. The image has more length and width; but that does not show. So, basically I am not being able to see full view of the picture though zooming. Can anybody help me to set this configuration? I tried multiple config, but did not work.
The following image has more height in the bottom, but it does not show while zooming. It only zoom on what is viewable here. Not sure if it supports this feature to see full dimension of the picture in zoom condition.

![image](https://user-images.githubusercontent.com/6777646/162169404-1d56f138-3659-47cf-bfb8-2fe5b78a0f2b.png)

**Comment by dtemir** [comment]
Hey! Did you ever find a fix for this?

**Comment by KarupoegPuhh** [comment]
i just set the width/height something less than the viewport initially and then proceed to zoom in for a workaround
