### ISSUE TITLE
I can't find the example code for the storybook examples ?

### ISSUE THREAD

**Issue by DVGY** [prc5/react-zoom-pan-pinch#296]
Where is the code section for all the examples in storybook ?

**Comment by janaagaard75** [comment]
Do you mean the `.stories.mdx` files?

**Comment by DVGY** [comment]
in most of the repo they have code sandbox, for each example where is the js file ?

**Comment by janaagaard75** [comment]
Are you looking for the JavaScript behind a page like [this one](https://prc5.github.io/react-zoom-pan-pinch/?path=/story/examples-controls--controls)? If so, the answer is, that most of that code comes from [Storybook](https://github.com/storybookjs/storybook/). I hope this helps.

**Comment by DVGY** [comment]
@janaagaard75  It will be much better if there is a code option 
![image](https://user-images.githubusercontent.com/46158826/176589091-4eebc3d6-5c51-4c03-b2e2-bea1154625cc.png)
