### ISSUE TITLE
Would it be okay to create a fork?

### ISSUE THREAD

**Issue by janaagaard75** [prc5/react-zoom-pan-pinch#299]
Hi @prc5. It seems that this repository hasn't received much attention lately, and I think that's a big shame because it's really great. We are planning on using it in our upcoming product at my work place.

Would it be okay if I create a fork and release as @company/react-zoom-pan-pinch? First and foremost the fork would fix the issue with the missing source files (#266), update dependencies to fix some of the security issues reported by Dependabot, and finally to ensure it works with React 18 and update the peer dependency (#292).

**Comment by janaagaard75** [comment]
I have released [@pronestor/react-zoom-pan-pinch](https://www.npmjs.com/package/@pronestor/react-zoom-pan-pinch) fork. So far it's just fixing #266.

**Comment by janaagaard75** [comment]
I will leave this issue open for while, so that @prc5 has a chance to see it.

**Comment by dtemir** [comment]
Thank you @janaagaard75. I'm still learning React and I really did not want to work this bug out :)

I think what you propose should be good because it's under the MIT license

**Comment by kasmoto** [comment]
Thank you so much for doing this @janaagaard75! A real shame that this library has not been given much attention.

**Comment by janaagaard75** [comment]
You're all welcome. I will pass it along to my boss for allowing me to use some of my time on open source.

There are two things that you can do to help:

1. See if there are any of the open pull requests to this repo that should be carried over to the fork. I believe that I have made a comment in here, in the ones that have been ported.
2. There are some bugs that have been reported, that I have yet had time to dig into. If you spend some time on a bug, and only find a partial solution, feel free to comment on the bugs, because your findings might make it easier to create a pull request with a fix.

**Comment by prc5** [comment]
@janaagaard75 I'm back with maintenence, thanks for helping! If you're interested in working on this, or merging your changes, we can talk about it 🙌🏻

**Comment by janaagaard75** [comment]
So great to hear that you're back, @prc5. I hope you're well. I would gladly help here, but I all honesty, the only real thing that I managed to change in the fork that I created, was to improve the parameters used in the Storybook stories a bit. It shouldn't be that hard to port these changes to this repo - I'll create a pull request.
