### ISSUE TITLE
Not working on react 18

### ISSUE THREAD

**Issue by Gyan555** [prc5/react-zoom-pan-pinch#310]
React-zoom-pan-pinch is not working properly on react 18 and giving warning and error in terminal.

**Comment by hadarhubara10** [comment]
Look in this issues
https://github.com/prc5/react-zoom-pan-pinch/issues/292

**Comment by janaagaard75** [comment]
This has been fixed in https://github.com/proNestorAps/react-zoom-pan-pinch.

**Comment by prc5** [comment]
This is fixed with the new version 2.2.0 of library.

**Comment by ravulask** [comment]
Team could you please help me with below issue please 

Issue: Once Image is zoomed it does not allow to Pan/move to certain area of image. It does work when i remove the code from Modal Tag. But I am showing image in a modal Pop up and allowing user to better zoom in image.

Code:
import React from "react";
import {
TransformWrapper,
TransformComponent,
useControls,
} from "react-zoom-pan-pinch";
//import { useId, useBoolean } from "@fluentui/react-hooks";
import { Modal } from "@fluentui/react";

function App() {
const Controls = () => {
const { zoomIn, zoomOut, resetTransform } = useControls();
return (
<>
zoomIn()}>Zoom In
zoomOut()}>Zoom Out
resetTransform()}>Reset
</>
);
};
return (




classname="SignatureImage1"
src="https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
alt="test"
width="100%"
/>



);
}
export default App;
