### ISSUE TITLE
Transform component re-renders many time affecting performance 

### ISSUE THREAD

**Issue by khoale012000** [prc5/react-zoom-pan-pinch#311]
I have a bunches of little image that need to render in the transform component and it seem like that its re-render many times when I am using the zoom and pan.  Even a single click causing it to re-render around 6 times.  This affecting performance and lagging.  I have tested with React 17 and 18 and it is doing the same. 

Does anyone experience this behavior?  Is there any work around that can minimize the number of render?.

**Comment by maxwellwalin** [comment]
Yes, I have the same issue as well. In my case, each child component I add to the TransformComponent decreases the performance exponentially. I am looking for a workaround too.

**Comment by rkvirajgupta** [comment]
same with me as well

**Comment by aexol** [comment]
Hi, @prc5 thank you for the great library. Do you know when the rerender issue will be solved? Do you know any possible workaround?

**Comment by prc5** [comment]
@aexol Hey! I will try to take a look this or next weekend 🙏

**Comment by prc5** [comment]
@aexol Actually I think I solved it today, I would be very glad if you will check the new version and let me know if it's fine.

**Comment by prc5** [comment]
Added "performance" prop, so you can disable rerenders when you don't need them.

**Comment by aexol** [comment]
Wow! So fast! Thank you so much, I will test now

**Comment by aexol** [comment]
![image](https://user-images.githubusercontent.com/779748/217234431-c46b0b10-bcff-4ff9-a7f6-2b39a72fc6db.png)
0.1ms compared to 10ms - Thank you!

**Comment by aexol** [comment]
I mean it was 10ms before now its 0.1ms
