### ISSUE TITLE
Not able to call zoomIn, zoomOut with useRef initially

### ISSUE THREAD

**Issue by ehsankhan-blitz** [prc5/react-zoom-pan-pinch#315]
In my Parent Component there are buttons to control zoomIn, zoomOut, and i am passing the ref to the child component  i.e. the zoom component, and setting the ref on TransformWrapper, but when i run the onClick on zoomIn the state changes but the image doesn't zoom.

**Comment by loo-ez** [comment]
Did you solve this issue?

**Comment by ehsankhan-blitz** [comment]
yes

**Comment by ShashanKV98** [comment]
Hi. I'm facing the same issue. Could you explain how you solved your problem? 
Thanks!

**Comment by ehsankhan-blitz** [comment]
Hi @ShashanKV98,
I saved the action in an state variable and passed the state to the child component and performed actions accordingly.
