### ISSUE TITLE
 Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by petvas** [prc5/react-zoom-pan-pinch#32]
I got this error message every time when I click on the page:
```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at getComponentsSizes (index.es.js:348)
    at StateProvider.handleCalculateBounds (index.es.js:380)
    at StateProvider._this.handleStartPanning (index.es.js:941)
getComponentsSizes @ index.es.js:348
handleCalculateBounds @ index.es.js:380
StateProvider._this.handleStartPanning @ index.es.js:941
15:33:48.257 
```

When I tried to debug I added:
`console.log("setWrapperComponent", wrapperComponent);` to StateContext.js
and my console show:
```
setWrapperComponent <div>​…​</div>
```
and few seconds later:
```
setWrapperComponent null
```
I think when `TransformWrapper` added with array map and we change the array that can cause an issue. I can't reproduce the issue outside of our codebase.

**Comment by prc5** [comment]
Could you check if it's still a problem with a new version?
