### ISSUE TITLE
Cannot change how quickly it zooms

### ISSUE THREAD

**Issue by Dcorb1209** [prc5/react-zoom-pan-pinch#33]
None of the "AnimationSpeed" props seem to work. Can someone help me zoom faster or slower?

Also, I noticed the within the source code, the animation speed props are set to PropTypes,bool instead of PropTypes.number could that be the issue? I did not trace the code any further.

**Comment by prc5** [comment]
Yeah, it's about being implemented, I will need some time to fully close the animations logic.

**Comment by Dcorb1209** [comment]
No worries, thank you for the reply. This library has been very helpful.
