### ISSUE TITLE
Build Error in Next.js project

### ISSUE THREAD

**Issue by guilhermeSuporteDev** [prc5/react-zoom-pan-pinch#332]
Hello, I recently added the react-zoom-pan-pinch library to my Next.js project, but now I am encountering an issue with running the build command. I receive the following error: "Type error: Cannot find module 'core/wheel/wheel.utils'.

It appears to be a reference error, as adding '"core/": ["node_modules/react-zoom-pan-pinch/src/core/*"]' to my compilerOptions in tsconfig.json allows the build to continue, but it then fails in the utils module, followed by the models module. I like the library's functionalities, but I can't use it in production like this.

I would like to know if there is a solution to this issue or if it needs to be fixed in the library. Any help would be greatly appreciated. Thank you!

**Comment by benrychter** [comment]
I also use Next.js (version `13.1.0`) but have no issues building an app.

**Comment by gregg-cbs** [comment]
I saw this issue and went to build my app, it builds fine.
Make sure you are using npm and not pnpm and try uninstalling the packages and reinstalling.
