### ISSUE TITLE
Very slow movement with SVG

### ISSUE THREAD

**Issue by RodeoAdrian** [prc5/react-zoom-pan-pinch#339]
Hello! I'm trying SVG and the movement is very laggy and slow, this is the performance tab while clicking and moving the svg:

![Screenshot 2023-02-17 at 13 16 39](https://user-images.githubusercontent.com/97752751/219707088-f5fcbe58-fc1c-42fd-88cc-3e820225f4de.png)

**Comment by prc5** [comment]
Can you provide part of your implementation?

**Comment by RodeoAdrian** [comment]
> Can you provide part of your implementation?

Sure

```javascript
<div
  style={{ width: width ? width : '768px', height: height ? height : '768px' }}
  className={`mapLoader mapLoader--${isLoaded ? 'loaded' : 'loading'} ${isErrored ? 'mapLoader--errored' : ''}`}>
  <TransformWrapper initialScale={1} initialPositionX={0} initialPositionY={0}>
    {({ zoomIn, zoomOut }) => (
      <React.Fragment>
        <div className="tools">
          <button onClick={() => zoomIn()}>+</button>
          <button onClick={() => zoomOut()}>-</button>
        </div>
        <TransformComponent wrapperStyle={{ width: '100%', height: '100%' }}>
          <div id="svg-map" className="svg-map arena-map visible" dangerouslySetInnerHTML={{ __html: svg }} onClick={handleClick}></div>
        </TransformComponent>
      </React.Fragment>
    )}
  </TransformWrapper>
</div>
```

As you can see, I have an `onClick` handler there, I'm making these SVGs interactive. I have other methods too, that as soon as the svg is loaded I add classes to some SVG elements, so in the same function I have:

```javascript
useLayoutEffect(() => {
  if (document && document.getElementById('map_svg') && firstRender) {
    setColors();
    disableBoxes();
    setFirstRender(false);
  }
});
```
`setColors` and `disableBoxes` are looping svg elements and adding just css classes if some external conditions apply. But that's it

`map_svg` is the actual id HTML attribute the real svg file has in its main tag

**Comment by AhmedBG** [comment]
Hello, I have the same problem (on mobile) when I updated to the version 2.6 today.

**Comment by prc5** [comment]
Hey guys, this problem will be solved in the new version of zoom pan pinch, it is related to the position tracking in the render props.

**Comment by AhmedBG** [comment]
> Hey guys, this problem will be solved in the new version of zoom pan pinch, it is related to the position tracking in the render props.

Thank you for your reactivity.
