### ISSUE TITLE
defaultPositionX & defaultPositionX are overwritten by dynamic values

### ISSUE THREAD

**Issue by christophcar** [prc5/react-zoom-pan-pinch#34]
**Bug:**

`defaultPositionX` and `defaultPositionY` are immediately overwritten by dynamic values when the components render.

**Expected behaviour:**

I would expect the defaultPosition (X, Y) values to be applied on initial rendering. For `defaultScale` this already works correctly.

**Comment by prc5** [comment]
It should be fine now 👍 Let me know if it's fixed in your case, because I had some work with other things and didn't have much time to spend on it

**Comment by beac0n** [comment]
I have the same issue with 1.6.1

**Comment by Batuhan-Akkaya** [comment]
same  issue with 1.6.1

**Comment by phillmill** [comment]
I tried a bunch of previous versions, and 1.5.5 is the most recent version I could find that defaultPositionX and defaultPositionY work correctly

**Comment by InfamousStarFox** [comment]
I also have this issue in v1.6.1

**Comment by InfamousStarFox** [comment]
Found a solution. See https://github.com/prc5/react-zoom-pan-pinch/issues/82#issuecomment-583891935

The defaults of:
limitToBounds: true
limitToWrapper: false
centerContent: true

Are causing this to fire in `src/store/StateContext.tsx`
```
if (
  (limitToBounds && !limitToWrapper) ||
  (centerContent && !positionX && !positionY)
) {
  const transform = `translate(25%, 25%) scale(${scale})`;
  ...
}
```

My solution was to override those default options like so:

```
<TransformWrapper
  defaultScale={5}
  defaultPositionX={-1200}
  defaultPositionY={-1200}
  options={{
    centerContent: false,
    limitToBounds: false
  }}
>
```
