### ISSUE TITLE
Reconfiguring zoom/pan controls

### ISSUE THREAD

**Issue by nikosmove** [prc5/react-zoom-pan-pinch#340]
Hi there

Just wondering, is it possible to reconfigure controls for zoom / pan to be like on Figma or Miro board, i. e. use Cmd/Ctrl key for zooming with scroll/trackpad and scroll/trackpad with no keys pressed just for panning? I haven't found this option in documentation.

**Comment by prc5** [comment]
Yes! There are activationKeys for each "section" like panning, wheel, pinch :)
