### ISSUE TITLE
Getting transformation values before they are applied

### ISSUE THREAD

**Issue by juliBotmaker** [prc5/react-zoom-pan-pinch#346]
**Is your feature request related to a problem? Please describe.**
In version 2.1.3 `handleRef` was called after applying the transformations to `contentComponent` styles but now in 3.0.0 `handleCallback` is called before `applyTransformation` and this causes that the transformation value I get is not the current one as it happened in the previous version

**Describe the solution you'd like**
swap `handleCallback` and `applyTransformation` position in `setTransformState`

**Describe alternatives you've considered**
create a new callback after `applyTransformation`

**Additional context**
![image](https://user-images.githubusercontent.com/88547741/221608553-24289dbc-76cc-499b-86f2-916a836ab5bc.png)

Thank you for this great library ❤️

**Comment by prc5** [comment]
@juliBotmaker thanks for the report!

**Comment by prc5** [comment]
@juliBotmaker deploying changes 🙌🏻
