### ISSUE TITLE
[question] Using current values of state with new hooks

### ISSUE THREAD

**Issue by ignlopezsanchez** [prc5/react-zoom-pan-pinch#350]
Hi!
I have been using this library since last year. In order to make it work for my project, I had a component where I was able to use:
```  
const { zoomToElement, state, setTransform, centerView } = useTransformContext();

```
This component is inside a TransformWrapper

As far as I can see in new hooks in v3.0.0, I need to use: 
```
const { zoomToElement, setTransform, centerView } = useControls();
 const { transformState } = useTransformContext();
```
Is this correct? The problem I have, it s that scale value of transformState is not being updated when I trigger a setTransform. Maybe the new useTransformContext needs to be inside TransformComponent??

But I think new useTransformContext does not render a new transformState now. My issue now is that I not use zoomIn, zoomOut. Y need to have full control of zoom values, so I use setTransformState from useControls and I pass x and y of current state and a new scale value (according to my own values)
```   

  const setTransformValues = (value: number) => {
       setTransform(transformState.positionX, transformState.positionY, value / 100);
  };
```
I have seen the new useTransformEffect in order to react to state changes.
But in my case, I need to define a function that later I pass to my custom zoom controls buttons, so I think it is not usefull for me.

Thanks!

**Comment by ignlopezsanchez** [comment]
I have been able to adapt it to work in my project but now a local state is needed.
Basically, I define a new useState and in the useTransformEffect I have to set the new state value in my local state. At the end I have the same renders I had in v2 but with a new local state.
I do not know if this could be improved some way. I understand these changes were made to avoid rerenders, but now for those who need full control of scale it is necessary more code and synchronize a local state and library state.

To be honest, I can't imagine now a better way to do it.
```
 useTransformEffect(({ state }) => {
    setCurrentStateValue({ ...state });
    return () => {
      // unmount
    };
  });
```
Thanks!

**Comment by prc5** [comment]
Hey @ignlopezsanchez! You can also use libraries like https://github.com/BetterTyped/react-performance-hooks which can give you throttled/debounced state. The idea behind this is that I do not force to use one way for the rerendering. You can use many techniques to optimize your code - with throttling or debouncing.
