### ISSUE TITLE
Large image doesn't pan properly

### ISSUE THREAD

**Issue by jasymons** [prc5/react-zoom-pan-pinch#351]
I'm trying to replicate the exact functionality from this example: [https://prc5.github.io/react-zoom-pan-pinch/?path=/story/examples-big-image--big-image](https://prc5.github.io/react-zoom-pan-pinch/?path=/story/examples-big-image--big-image) with a large image, but panning is not initially possible past the viewport size. If you zoom in, you can pan around, but only around the section of the image that's already viewable within the viewport, the rest is cut off. How can the same effect as the example be achieved, what props or extra styling are used here?

**Comment by prc5** [comment]
Hey @jasymons! I believe you just need to wrap it into some div which will adjust to the viewport of your site. 

```tsx
<div style={{ maxWidth: "100%" }}> // -> here you need to control the max size to fit into your page
    <TransformWrapper>
       // your code
    </TransformWrapper>
</div>
```
