### ISSUE TITLE
Style TransformWrapper

### ISSUE THREAD

**Issue by Sp1d3rbite** [prc5/react-zoom-pan-pinch#355]
Hi there,

Recently I've started using this but am unfortunately unable to find how to style the TransformWrapper component.
I've run into the issue that a tall image will extend beyond the screen and thus being unable to pan all the way down.
Setting the height to a manual pixel height in the browser console works as intended, but I am unable to do the same thing in code.

Below is what I have tried so far:
`<TransformWrapper
                    initialScale={1}
                    initialPositionX={0}
                    initialPositionY={0}
                    style={{height: '300px'}}
                >`

Is there any way to do this that I am overlooking?

**Comment by prc5** [comment]
Hey @Sp1d3rbite, you should add it to the <TransformComponent wrapperStyle={{...}} /> or just to use css on it's class 👍🏻

**Comment by Sp1d3rbite** [comment]
Hey @prc5, thanks for the swift reply!

Adding some css to the react-transform-wrapper class seems to be working!
I am however interested in the other way you mentioned, I'm sorry, but it wasn't clear from your answer above.
