### ISSUE TITLE
Click event not work in TransformComponent with image tag

### ISSUE THREAD

**Issue by jiachaosun** [prc5/react-zoom-pan-pinch#37]
I know the click event is right in the div demo, but when I have a image component in the TransformComponent and set onClick in the image or have a map and some areas attrs, the click event did not work.

```
            <img
              src={require('./images/map.jpg')}
              useMap="#image-map"
              onClick={() => alert(1)}              // <---- not work
            />
            
            <map name="image-map">
              <area
                coords="751,538,846,640"
                shape="rect"
                onClick={() => alert(1)}             // <----- not work either
              />
```

**Comment by prc5** [comment]
Hey! This is strange, I'm working on new version of the lib and it is working there, at least it is working on the example component :) It will be out in about 2 days
