### ISSUE TITLE
Not Working on Chrome 30 Browser - need to add CSS Prefix(-webkit-transform)

### ISSUE THREAD

**Issue by sanjuvcs** [prc5/react-zoom-pan-pinch#39]
<img width="1178" alt="Screen Shot 2019-11-11 at 5 13 11 PM" src="https://user-images.githubusercontent.com/11405878/68584804-9b037a00-04a6-11ea-81af-9f177a718204.png">
Hi Team,

React zoom pan pinch is not supporting on the chrome old browser. so please add WebKit transform for TransformComponent( in react-transform-element class).

Kindly do the needful. Thank you for your support.

**Comment by selvambe23** [comment]
I have fixed this issue in this PR
https://github.com/prc5/react-zoom-pan-pinch/pull/40

**Comment by prc5** [comment]
Thanks! It is out with 1.3.1 version 👍

**Comment by sanjuvcs** [comment]
Thanks, but while trying to downloading the 1.3.1 version not supported and showing below error.

<img width="711" alt="Screen Shot 2019-11-12 at 11 56 46 AM" src="https://user-images.githubusercontent.com/11405878/68647375-c0929100-0543-11ea-9e0d-81a664bda57e.png">

Kindly do the needful. Thank you for your support.
