### ISSUE TITLE
Reproducing responsive-image behavior

### ISSUE THREAD

**Issue by gaelhelle** [prc5/react-zoom-pan-pinch#402]
Hey!

I've been trying a bit but can't manage to reproduce the "responsive-image" behavior here: https://prc5.github.io/react-zoom-pan-pinch/?path=/story/examples-responsive-image--responsive-image

Is there some custom calculation involved to get the image to fit within the wrapper on load?

Thanks

**Comment by thelornenelson** [comment]
@gaelhelle I had the same question and turns out yes, there's a bunch of custom stuff going on. You can view the code for that example at https://github.com/prc5/react-zoom-pan-pinch/blob/master/src/stories/examples/image-responsive/example.tsx

**Comment by gaelhelle** [comment]
Thanks @thelornenelson, closing this!
