### ISSUE TITLE
textarea or input can't be select the context inside by mouse move

### ISSUE THREAD

**Issue by leosuoxxo** [prc5/react-zoom-pan-pinch#44]
hi ~
I thought it will cause the whole app has this issue.

![image](https://user-images.githubusercontent.com/24968893/68836552-9680d080-06f5-11ea-9ff3-e6cfb83f5196.png)

**Comment by prc5** [comment]
I've just added 'disableOnTarget' prop - you put there an array of class names or tags you want to exclude from panning function to fire :)
