### ISSUE TITLE
Zooming issues when TransformComponent larger than TransformWrapper

### ISSUE THREAD

**Issue by justinc11** [prc5/react-zoom-pan-pinch#49]
I am working on a project where I would like to provide zooming and panning for images that could be of any size. I have set a size on a div inside of the `TransformWrapper` to restrict the zooming and panning area to within the width and height of the screen. However, sometimes the images inside the `TransformComponent` can be larger than the screen. In this scenario, it seems to center the images within the larger element rather than the smaller one, causing parts of the image to not be reachable within the zooming area.

It is important for me to initially show the user the image at the original size so scaling them down is not really an option.

Below is an example using divs that reproduces the error. See the issue in [code sandbox](https://codesandbox.io/s/crazy-newton-gn53d)

```jsx
import React from 'react';

import { TransformWrapper, TransformComponent } from "react-zoom-pan-pinch";

export default function Example(){
  return (
    <TransformWrapper 
      defaultScale={0.3} 
      options={{
        minScale: 0.1, 
        // false for centerContent does not seem to work except at initial render?
        // centerContent: false
        // true seems to center it with the TransformComponent-module_container__XXX 
        // which causes it to be off-center
        centerContent: true 
      }}>
      {({ zoomIn, zoomOut, resetTransform, ...rest }) => (
        <React.Fragment>
          <div style={{textAlign: 'left'}}>
            <div>Orange = Zooming Area; Blue = Object being zoomed</div>
            <button onClick={zoomIn}>+</button>
            <button onClick={zoomOut}>-</button>
            <button onClick={resetTransform}>x</button>
          </div>
          {/* Set zooming area size. Tried with sizing div outside/inside/inside and outside of TransformComponent */}
          <div style={{height: 510, width: 510, backgroundColor: 'orange', border: '10px solid green'}}> 
            <TransformComponent>
              {/* Thing I am actualy trying to zoom. Potentially bigger than TransformComponent parent */}
              <div style={{height: 1000, width: 1000, backgroundColor: 'blue', border: '50px solid'}} />  
            </TransformComponent>
          </div>
        </React.Fragment>
      )}
    </TransformWrapper>
  );
}
```

Changing the height/width properties for `TransformComponent-module_container__XXX` in the browser from `fit-content` to `100%` seems to make the issue a little better, but it is still not perfectly centered and I'm not sure of the implications of this.

Here is what is rendered after zooming out some.

![image](https://user-images.githubusercontent.com/18541397/69185706-34551080-0ae5-11ea-946c-c8d7a0309135.png)

After setting the `TransformComponent-module_container__XXX` div to have a 100% size:

![image](https://user-images.githubusercontent.com/18541397/69185822-6fefda80-0ae5-11ea-8e8c-c96715fbefb4.png)

**Comment by prc5** [comment]
Hey, thanks for reporting! To be honest I made it intentional because it was easier for development to focus on components that are no larger than the size of the wrapper. Now, however, the logic is refined and extension should be possible. I will try to finish it over the weekend 👍
