### ISSUE TITLE
npm/yarn version1.5.5 is different from github

### ISSUE THREAD

**Issue by piemonSong** [prc5/react-zoom-pan-pinch#66]
Hi, npm/yarn version1.5.5 is different from github.
 i.e. TransformWrapper.d.ts `import { TransformWrapperProps } from "../store/interfaces/transformWrapperInterface";`. But _transformWrapperInterface_ is not exist. 
I'm just a little confused

**Comment by RikuMantysalo** [comment]
Got the same error with `npm install react-zoom-pan-pinch` and `npm install prc5/react-zoom-pan-pinch#master` which installs the package from the master branch of this repo. 

Seems like it could be a problem with the bundling/build as the file is included in the `src` directory but not in the `dist` directory.

```bash
$ npm --version
6.11.3
$ node --version
v10.10.0
```

**Comment by prc5** [comment]
I will try to fix it over the weekend, thanks for reportinh
