### ISSUE TITLE
How can I rotate the image with keeping aspect ratio?

### ISSUE THREAD

**Issue by mikusjozsefevista** [prc5/react-zoom-pan-pinch#69]

**Comment by prc5** [comment]
You need to save the transform values and add to them rotate value - something like "transform: translate(0,0) scale(1) rotate(20deg)"

**Comment by Ashkanph** [comment]
I did this, but it still doesn't keeping the aspect ratio (rotateDegree changing dynamically):

`<TransformWrapper>
      {({ positionX, positionY, scale }) => (
            <>
                 <TransformComponent>
                        <img
                             className="image"
                              src={TestImage}
                              style={{transform: `translate(${positionX},${positionY}) scale(${scale}) rotate(${rotateDegree}deg)`}}
                  </TransformComponent>
            </>
       )}
</TransformWrapper>`

**Comment by franciscalizo2** [comment]
> I did this, but it still doesn't keep the aspect ratio (`rotateDegree` changes dynamically):
> 
> ```js
> <TransformWrapper>
>    {({ positionX, positionY, scale }) => (
>         <>
>              <TransformComponent>
>                   <img
>                        className="image"
>                        src={TestImage}
>                        style={{transform: `translate(${positionX},${positionY}) scale(${scale}) rotate(${rotateDegree}deg)`}}
>               </TransformComponent>
>         </>
>     )}
> </TransformWrapper>
> ```

Hi! Did you ever resolve this issue? I'm running into the same problem.
