### ISSUE TITLE
Problem if use in TS context

### ISSUE THREAD

**Issue by PooLP** [prc5/react-zoom-pan-pinch#77]
Hi,
There is a problem with Type on TransformComponent component in TS context (class component)

> error :
> Type 'TransformComponent' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.ts(2605)

https://codesandbox.io/s/boring-firefly-u35d3

Do you have an idea of the problem ?
Thanks.

**Comment by prc5** [comment]
I don't know at the moment, but I will check this out

**Comment by h3nn3** [comment]
@PooLP Modifying my tsconfig helped me with this issue: 
`"allowSyntheticDefaultImports": true /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */`

**Comment by PooLP** [comment]
@h3nn3 : thanks, this is what i also did while waiting for the bug to be fixed ;)
