### ISSUE TITLE
TypeError: Cannot read property 'offsetWidth' of null

### ISSUE THREAD

**Issue by yossi-shasho** [prc5/react-zoom-pan-pinch#81]
After upgrading from version 1.0.0 to 1.6.1 I get the following error:
```
TypeError: Cannot read property 'offsetWidth' of null
getComponentsSizes
node_modules/react-zoom-pan-pinch/dist/index.es.js:484
  481 | }
  482 | 
  483 | function getComponentsSizes(wrapperComponent, contentComponent, newScale) {
> 484 |   var wrapperWidth = wrapperComponent.offsetWidth;
  485 |   var wrapperHeight = wrapperComponent.offsetHeight;
  486 |   var contentWidth = contentComponent.offsetWidth;
  487 |   var contentHeight = contentComponent.offsetHeight;
```
just using the basic setup from the GitHub example.

**Comment by madeeha96** [comment]
I was facing same issue. I resolved this issue by passing children component between TransformComponet

 <TransformComponent>
{props.children}</TransformComponent>

**Comment by jsveron23** [comment]
I guess your image was not load somehow before trying to get offset props

**Comment by benjaminsuch** [comment]
Reason is, that the component which uses `TransformWrapper` has to be a class component.

**Comment by eugenegodun** [comment]
It's still an issue for me. @prc5 do we know how to solve it? Sometimes it fails for some images
