### ISSUE TITLE
PositionX and PositionY are ignored on mount 

### ISSUE THREAD

**Issue by zadremal** [prc5/react-zoom-pan-pinch#82]
PositionX and PositionY make no difference on component mounting with nested image 

Quick demo :
https://codesandbox.io/s/empty-wind-shhik?fontsize=14&hidenavigation=1&theme=dark

**Comment by colshacol** [comment]
Seems like scale and defaultScale are not applied on mount, as well.

**Comment by michu2k** [comment]
Any fix for this @prc5 ?

**Comment by zadremal** [comment]
I had looked through the source code and found the problem. in StateContext.tsx setContentComponent method changes translate parameter to 25% under these conditions: 
`      const { positionX, positionY } = this.props.defaultValues;

      if (
        (limitToBounds && !limitToWrapper) ||
        (centerContent && !positionX && !positionY)
      ) {
    `
with default props this condition is always true. 
Changing limitToWrapper to true solves the problem

**Comment by ferezoz** [comment]
For me the fix was to set `centerContent: false`
