### ISSUE TITLE
Failed to execute 'requestAnimationFrame' on 'Window' when storing zoom level in state

### ISSUE THREAD

**Issue by henrikrudstrom** [prc5/react-zoom-pan-pinch#84]
I get this error when i use the onZoomChange to store the current zoom level in my components state.
this is an extract of my code, if i comment out the `setZoom()` statement below it works fine again.

```
    ....
    const [zoom, setZoom] = useState<number>();
    const zoomChange = ({ scale }) => {
        console.log('zoom', scale);
        setZoom(scale);
    };

    return (
        <SelectionProvider>
            <TransformWrapper {...opts} onZoomChange={zoomChange}>
                {({ zoomIn, zoomOut, resetTransform }) => (
                    <>
                        <TransformComponent>
                            <div className="graphView__container">
                                <Graph
                                    graph={graph}
                                    bounds={graphBounds}
                                    zoom={zoom || 1}
                                />
                            </div>
                        </TransformComponent>
                        <ToolButtons
                            zoomIn={zoomIn}
                            zoomOut={zoomOut}
                            resetTransform={resetTransform}
                        />
                    </>
                )}
            </TransformWrapper>
    );
```

```
TypeError: Failed to execute 'requestAnimationFrame' on 'Window': The callback provided as parameter 1 is not a function.
animation
src/store/animations/index.ts:35
    32 |     this.animation = null;
    33 |   } else {
    34 |     callback(step);
  > 35 |     requestAnimationFrame(this.animation);
    36 | ^  }
    37 | };
    38 | 
```

**Comment by DannyelPina** [comment]
I have the same problem in my project... If you found a way to solve it, please let me now what

**Comment by bright-wang** [comment]
@DannyelPina @prc5 I came up with the similar problem ,too. I think it's because 'this.animation = null;' is executed and then call requestAnimationFrame(this.animation); the first argument is null already.It's a bug and should be fixed.

**Comment by edwinlimlx** [comment]
facing same issue =( any quick workarounds?

**Comment by pasierb** [comment]
I have the same issue only when 'onZoomChange' is set on TransformWrapper. Without it works as expected.

**Comment by pasierb** [comment]
> facing same issue =( any quick workarounds?

@edwinlimlx  a quick workaround that worked for me was to use function child (or whatever it's called in react world)

```jsx
<TransformWrapper
        defaultScale={1}
        options={{
          minScale: 0,
          centerContent: true,
          limitToBounds: false
        }}
      >
        {({ resetTransform, zoomIn, zoomOut, scale }) => (
           ...
```

**Comment by iainrj** [comment]
I found that a way to mitigate this error occuring was to reduce how often I was setting the state. In my case I only wanted to know if the `scale` value was 1 or 2, i.e default or 2x zoomed. 

```js
  const [zoom, setZoom] = useState(1);

  function setZooming(e) {
    if (e.scale === 2 && zoom !== 2) {
      setZoom(2)
    } else if (e.scale === 1 && zoom !== 1) {
      setZoom(1);
    }
  };
```

This seems to stop the error from occurring and allow you to use `onZoomChange` on the `TransformWrapper`. Hope this helps anyone with a similar problem!

**Comment by frxzn** [comment]
I needed to toggle between zoomIn/reset mode on `doubleClick` depending on the zoom state. I was getting the same error, so what I did is to wait for the animation to finish (which defaults to 200ms) before setting the state, using `setTimeout`

```javascript
const [zoom, setZoom] = useState(false);

const handleZoom = (e) => {
    if (e.scale > 1 && !zoom) {
      setTimeout(() => {
        setZoom(true);
      }, 200);
    } else if (e.scale === 1 && zoom) {
      setZoom(false);
    }
  };

<TransformWrapper
    onZoomChange={handleZoom}
    doubleClick={{ mode: zoom ? 'reset' : 'zoomIn' }}
>
   ...
```

**Comment by JamesTheBald** [comment]
As with #pasierb, this problem also went away for me when I removed 'onZoomChange' from the wrapper. I replaced it with OnWheel.
