### ISSUE TITLE
Callback for dragging start and stop

### ISSUE THREAD

**Issue by maLikiz** [prc5/react-zoom-pan-pinch#85]
Hello. I have a simple interactive SVG map, I would like to have dragging callbacks to toggle `pointer-events: none`, to prevent clicking  to buttons in during of dragging. That is, I need to know when I click and move the mouse. `onPanningStart` works when clicked only without waiting for mouse movement

**Comment by jslyonnais** [comment]
Hey mate!
Found out a way to do this super easy ;-)

Setup the origin of your X,Y and compare it while moving. If it's not the same, add your `pointer-events: none`

Here's an example with React hook.

```javascript
const [ canvasX, setCanvasX ] = useState(0)
const [ canvasY, setCanvasY ] = useState(0)
const setPositionChange = (e) => {
  setCanvasX(e.positionX)
  setCanvasY(e.positionY)
}


<TransformWrapper
  onPanningStart={(e) => setPositionChange(e)}
  onPanningStop={(e) => setPositionChange(e)}
>
  {({ positionX, positionY, zoomIn, zoomOut, ...rest }) => (
    <TransformComponent>
      <div className={(positionX !== canvasX || positionY !== canvasY)? "locked" : ""}>Your content here!</div>
    </TransformComponent>
  )}
</TransformWrapper>
```
