### ISSUE TITLE
return functions from onZoomChange

### ISSUE THREAD

**Issue by japhex** [prc5/react-zoom-pan-pinch#88]
Hey! Are there any return functions from onZoomChange?

I can only see data about the zoom, but I want to say 'when the zoom hits a scale of 8, reset/zoomOut' and can't seem to find anything

**Comment by fraserisland** [comment]
Hey @japhex!
I easily achieved this by storing the scale in state, then changing the doubleClick mode depending on that scale. Here's some code: 

Store scale in state: 
` const [scale, setScale] = React.useState(0)`

Feeding TransformWrapper these props: 
`` <TransformWrapper
            onPanningStop={({ scale }) => setScale(scale)}
            doubleClick={{ mode: `${scale > 2 ? "reset" : "zoomIn"}` }}>
``
