### ISSUE TITLE
PositionX and PositionY after dragging

### ISSUE THREAD

**Issue by h3nn3** [prc5/react-zoom-pan-pinch#89]
The functions onPanning and onPanningStop are not returning the "end" x/y coordinates. 
The "problem" is the smooth sliding animation at the end of a panning (even when dragging the image outside of the wrapper div the image will snap back in place). 
PanningStop gets called after the user releases the mouse but we do not have a function that will deliver the exact end coordinates.

Don't get me wrong is still want to have the sliding animation but i need to know the exact coordinates like the DOM-element with the class _react-transform-element_.

Is there away to achieve this?

Thx and greetings :)

**Comment by CrzongA** [comment]
Sorry for "necroing" this issue, I am looking for a similar feature in this library, which is a way to return or retrieve the end transform via a method or hook. I am not seeing any in the class declaration that can achieve this, can somebody shed some light on this matter please?
