### ISSUE TITLE
render zoom actions buttons outside of component

### ISSUE THREAD

**Issue by soundquiet** [prc5/react-zoom-pan-pinch#91]
Hi, I'd like to know if it is possible to use the `zoom / setScale ` props in buttons outside of the component, instead of rendering them in it? thanks!!

**Comment by chienweiluo** [comment]
I need this too. Does anyone have the workaround?
Many thanks.

**Comment by chetan-annexlogics** [comment]
if it is possible to use the zoom / setScale props in buttons outside of the component

**Comment by prc5** [comment]
Hey I've added ref support now
