### ISSUE TITLE
function fall with setState in the same time

### ISSUE THREAD

**Issue by soundquiet** [prc5/react-zoom-pan-pinch#92]
Hi, if I add setState along with setTransfrom, it would make all out of work.
like`<button onClick={()=>{setTransform(0, 0, 1.2, 700, 'easeOut'); this.setState({click: 'true'})}}>+</button>`

here's the demo
https://codesandbox.io/s/react-to-print-y0t7j

EDIT:
It seems the animation duration caused it. replace 700 to 0 can fix it.

But how can I remain the duration for transition?

**Comment by cmunns** [comment]
I put the setTransform function inside a timeout and it seemed to force some sort of sync fix.
