### ISSUE TITLE
Panning not working on popped out window

### ISSUE THREAD

**Issue by felgoe** [prc5/react-zoom-pan-pinch#93]
I'm using this library in conjunction with [react-popout-component](https://github.com/microsoft/react-popout-component) to render an image in a popped out window.

While the actions bound to buttons work fine (such as resetTransformation, zoomIn, zoomOut) and double-click to zoom also works, the panning does not work.

Here is an example: https://codesandbox.io/s/still-leaf-t3shu

Any idea, why this might be the case?

**Comment by cj-l** [comment]
Any answer to this?
