### ISSUE TITLE
Is it possible to expand the item to cover the full screen 

### ISSUE THREAD

**Issue by alex-mironov** [prc5/react-zoom-pan-pinch#97]
I'd like to use the library to achieve zoom in/out effect for the plates and expand them into the full screen. Is it possible to achieve a similar effect to the one here https://work.co/ ? I would really be grateful to hear from you.

**Comment by udayakumarswamy** [comment]
+1

**Comment by prnv241** [comment]
same

**Comment by max-koa** [comment]
same
