### ISSUE TITLE
Can't get disableOnTarget prop working

### ISSUE THREAD

**Issue by kylekirkby** [prc5/react-zoom-pan-pinch#98]
Hi @prc5,

Thanks for the awesome open source project :D I'm trying to get the `disableOnTarget` option working so that a canvas inside of the wrapper is usable. I was hoping that upon clicking inside the canvas the panning would be disabled. I'm using a fabricjs canvas.

```jsx
              <TransformWrapper pan={{
                    disabledOnTarget: ["canvas_editor"],
                  }}>
                <TransformComponent>
                  <div className="canvas_editor">
                    <canvas {...css(styles.templateEditor)} id="template_editor" className="" />
                  </div>
                </TransformComponent>
              </TransformWrapper>

```

Does this look like it should work? 

Thanks in advance and cheers! 

Kyle

**Comment by obryl** [comment]
+1
Facing the same issues. Seems like disableOnTarget is not even on interface.

**Comment by holgerschillack** [comment]
Has anyone got that disableOnTarget option working? The transformer seems to ignore the set classes :(

**Comment by obryl** [comment]
Got it to work with 

```
const panOptions = {
            disableOnTarget: ['select-area'],
        } as any;
```

where select-area is css class. Also was needed to add `@ts-ignore` for `pan` property definition

**Comment by holgerschillack** [comment]
Hmm I'm using it in my plain JS react project

` <div style={{position: "absolute"}} className="stage">
[CONTENT]
</div>
`

and with

`  panOptions = {
    velocity: false,
    disableOnTarget: ["stage"],
  };`

and

`      <TransformWrapper
        options={{limitToBounds: false, minScale: 0.25, maxScale: 5.0}}
        defaultScale={1}
        defaultPositionX={0}
        defaultPositionY={0}
        pan={this.panOptions}
        wheel={{step: 500.0}}
      >`

is doesn't work, but the velocity option is working,

**Comment by franklinbravo** [comment]
> Hola @ prc5 ,
> 
> Gracias por el increíble proyecto de código abierto: D Estoy tratando de hacer que la `disableOnTarget`opción funcione para que se pueda usar un lienzo dentro del contenedor. Esperaba que al hacer clic dentro del lienzo, la panorámica se deshabilitara. Estoy usando un lienzo de fabricjs.
> 
> ```js-jsx
>               < TransformWrapper  pan = { {
>                      disabledOnTarget : [ " canvas_editor " ], 
>                   } } > 
>                 < TransformComponent > 
>                   < div  className = " canvas_editor " > 
>                     < canvas  { ... css ( styles . TemplateEditor ) }  id = " template_editor " className = " " /> 
>                   </ div > 
>                 </ TransformComponent > 
>               </ TransformWrapper >
> ```
> 
> ¿Parece que esto debería funcionar?
> 
> Gracias de antemano y saludos!
> 
> Kyle
Hi


> Hi @prc5,
> 
> Thanks for the awesome open source project :D I'm trying to get the `disableOnTarget` option working so that a canvas inside of the wrapper is usable. I was hoping that upon clicking inside the canvas the panning would be disabled. I'm using a fabricjs canvas.
> 
> ```js-jsx
>               <TransformWrapper pan={{
>                     disabledOnTarget: ["canvas_editor"],
>                   }}>
>                 <TransformComponent>
>                   <div className="canvas_editor">
>                     <canvas {...css(styles.templateEditor)} id="template_editor" className="" />
>                   </div>
>                 </TransformComponent>
>               </TransformWrapper>
> ```
> 
> Does this look like it should work?
> 
> Thanks in advance and cheers!
> 
> Kyle

Hi!
It is necessary to place the class specifically to the element you want, in your case place a className to the canvas with the same name you placed in disableOnTarget, you can also use the tagName

Example
> 
> ```js-jsx
>               < TransformWrapper  pan = { {
>                      disableOnTarget : [ " canvas_editor " ], 
>                   } } > 
>                 < TransformComponent > 
>                   < div > 
>                     <canvas  className = "canvas_editor "  { ... css ( styles . TemplateEditor ) }  id = " template_editor "  /> 
>                   </ div > 
>                 </ TransformComponent > 
>               </ TransformWrapper >
> ```
> 

or

> 
> ```js-jsx
>               < TransformWrapper  pan = { {
>                      disableOnTarget : [ "canvas" ], 
>                   } } > 
>                 < TransformComponent > 
>                   < div   > 
>                     <canvas    { ... css ( styles . TemplateEditor ) }  id = " template_editor " /> 
>                   </ div > 
>                 </ TransformComponent > 
>               </ TransformWrapper >
> ```
>
